# Site settings
title: Victor Freriks
email: vfreriks@gmail.com
description: "Front End Webdeveloper"
baseurl: ""
url: "http://victorfreriks.net"
twitter_username: vicvicvic
github_username:  vfreriks

# Build settings
markdown: kramdown
permalink: pretty